# Generated by Django 2.2 on 2019-11-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191103_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='about'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gitProfile',
            field=models.URLField(blank=True, null=True, verbose_name="github's profile"),
        ),
    ]
