# Generated by Django 2.2 on 2019-11-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191104_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='user_pics/angry_cat.jpg', null=True, upload_to='user_pics', verbose_name='Аватар'),
        ),
    ]
