# Generated by Django 2.2 on 2019-10-17 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20191017_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Type'),
        ),
    ]
