# Generated by Django 2.2 on 2019-10-17 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_task_updated_at'),
        ('webapp', '0007_auto_20191017_0100'),
    ]

    operations = [
    ]
