# Generated by Django 2.2 on 2019-11-04 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0009_auto_20191017_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(auto_now_add=True, verbose_name='Start Date')),
                ('finished_at', models.DateField(auto_now_add=True, verbose_name='Finish Date')),
                ('project_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Project')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
