# Generated by Django 2.2 on 2019-11-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
